// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GTAVehicles.Models
{
    public partial class GtaplayerCharacters
    {
        public GtaplayerCharacters()
        {
            GtaplayerGarages = new HashSet<GtaplayerGarages>();
        }

        public int Id { get; set; }
        public string CharacterName { get; set; }
        public string CharacterColor { get; set; }
        public int? PlayerId { get; set; }

        public virtual Gtaplayers Player { get; set; }
        public virtual ICollection<GtaplayerGarages> GtaplayerGarages { get; set; }
    }
}