// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GTAVehicles.Models
{
    public partial class Gtaplayers
    {
        public Gtaplayers()
        {
            GtaplayerCharacters = new HashSet<GtaplayerCharacters>();
        }

        public int Id { get; set; }
        public string UserName { get; set; }

        public virtual ICollection<GtaplayerCharacters> GtaplayerCharacters { get; set; }
    }
}